# Configuração do Air
root = "."  
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main.exe ."
bin = "tmp/main.exe"
delay = "1000ms"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]
exclude_file = ["README.md"]

[log]
time = true